### ISSUE TITLE
Drivers not working in Vitis 2024.2

### ISSUE THREAD

**Issue by obruendl** [patrick-studer/xtools#8]
I added a driver and pass a GUI parameter to xparameters.h. I get the following error when generating the Vitis BSP:

incrementer_g.c:23:1: error: unknown type name 'incrementer_Config'

I have attached the IP including the packaging script and the corresponding HW export.

[bd_wrapper_solution.zip](https://github.com/user-attachments/files/21384862/bd_wrapper_solution.zip)

[ip_solution.zip](https://github.com/user-attachments/files/21384843/ip_solution.zip)

I might just do something wrong. Please let me know if this is the case.

**Comment by obruendl** [comment]
I also noticed the entries in the xparameters.h are missing.

**Comment by patrick-studer** [comment]
@obruendl 

Thanks for using the XTOOLS IP-Packager 👍🏻 

> incrementer_g.c:23:1: error: unknown type name 'incrementer_Config'

I could reproduce the problem with Vitis Classic 2024.1 (2024.2 is not yet installed).

The problem comes from the auto-generated "Driver Config-File" => _incrementer_g.c_, which is created when the Platform is compiled. This files expects an type-definition of the _incrementer_Config_ struct inside _incrementer.h_.

I did not notice, that Xilinx does not auto-create the type definition and I will see if it is possible (or add a feature to code it automatically).

Since the Driver Config-File is only a extra-feature (to be as close as possible to Xilinx IP Cores), I can safely remove it until I found a fix. I pushed a fix to https://github.com/patrick-studer/xtools/tree/8-drivers-not-working-in-vitis-20242 (only commenting out the file creation in the driver TCL snippet).

Could you please test this state if it resolves your Platform compiler problem?

> I also noticed the entries in the xparameters.h are missing.

After removing the Driver Config-File generation, the platform project is compiling successfully in Vitis Classic 2024.1.

<img width="574" height="231" alt="Image" src="https://github.com/user-attachments/assets/df63f66f-f5d3-4c89-aba4-bccb920c70cc" />

If you are still missing the entries to the _xparameters.h_ file, it must be related to Vitis Classic 2024**.2**! Please let me know if so, then I will install the 2024.2 version and try to find out why...

**Comment by patrick-studer** [comment]
@obruendl 

Could you verify the patch? The "Driver Config File" (_g.c) is now disabled, what leaves the freedom to the user to implement it is his own code if required.

But the topic about missing xparameters.h entries and failing compilation should be resolved now, is it?

**Comment by patrick-studer** [comment]
@obruendl 
With the change provided [here](https://github.com/patrick-studer/xtools/compare/main...8-drivers-not-working-in-vitis-20242#diff-58c50c93ebeeb8409051e239b4bf725c6ea8903ee9b6f219adaed3ed0ba35d27R12) the _g.c file is not created.

In this case your IP Driver should compile successfully without the need of defining extra structs in the header file...
And everything should be fine in xparameters.h...

Did you test the patch - can I merge it?
